# Defaults can be found here: https://github.com/bbatsov/rubocop/blob/master/config/default.yml

# If you don't like these settings, just delete this file :)
AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'

Style/SpecialGlobalVars:
  Enabled: false
